src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ETSDepartmentCode__c</fullName>
        <label>ETS GRE Department Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ETSInstitutionalCode__c</fullName>
        <label>ETS GRE Institutional Code</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>College</fullName>
        <active>true</active>
        <description>Test</description>
        <label>College</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CollegeApplication__c.object
<CustomObject>
    <fields>
        <fullName>College__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>College</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>College Applications</relationshipLabel>
        <relationshipName>College_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>College Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>College Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CollegeDetailInlineExt.cls
public class CollegeDetailInlineExt{
    public Account College{get;set;}
    public Boolean EditMode{get;set;}
    public CollegeApplication__c collegeApp{get;set;}
    public CollegeDetailInlineExt(ApexPages.StandardController sc){
        List<String> lstOfCollegeAppFields = new List<String>{'College__c'};
        sc.addFields(lstOfCollegeAppFields );
        collegeApp = (CollegeApplication__c)sc.getRecord();
        editMode = false;
        college = new Account();
        
        if(collegeApp.College__c != null){
            college = [SELECT Id,Name,ETSInstitutionalCode__c, ETSDepartmentCode__c, Description FROM Account WHERE Id = :collegeApp.College__c];
        }
        
    }
    
    public void saveAccount(){
        update college;
        editMode=false;
    }
    public void editAccount(){
        editMode = true;
    }
    public void cancelEdit(){
        editMode=false;
    }
}