src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Interested__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Interested?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>YocketLink__c</fullName>
        <label>Yocket Link</label>
        <type>Url</type>
    </fields>
    <recordTypes>
        <fullName>College</fullName>
        <active>true</active>
        <description>Test</description>
        <label>College</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CollegeApplication__c.object
<CustomObject>
    <fields>
        <fullName>College__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>College</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>College Applications</relationshipLabel>
        <relationshipName>College_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HomePage__c</fullName>
        <formula>College__r.Website</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Home Page</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsInactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsInactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LoginPage__c</fullName>
        <label>Login Page</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Discovery/Initial Analysis</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Shortlisted</fullName>
                </value>
                <value>
                    <fullName>Shortlisted &amp; Signed Up</fullName>
                </value>
                <value>
                    <fullName>SOP/LOR In Progress</fullName>
                </value>
                <value>
                    <fullName>Application In Progress</fullName>
                </value>
                <value>
                    <fullName>Application Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WindowOpen__c</fullName>
        <label>Window Open</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>YocketLink__c</fullName>
        <label>Yocket Link</label>
        <type>Url</type>
    </fields>
    <label>College Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>College Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CollegesAtAGlanceController.cls
public class CollegesAtAGlanceController {

    public List<CollegeApplicationWrapper> lstCollegeApplicationWrapper {get;set;}
    public String rowCollegeAppId {get;set;}
    public String rowCollegeAppSaveId{get;set;}
    public String rowCollegeAppCancelId{get;set;}
    public CollegesAtAGlanceController(){
        lstCollegeApplicationWrapper = new List<CollegeApplicationWrapper>();
        Map<Id,Account> mapInterestedColleges = new Map<Id,Account>([SELECT Id,Rating,Interested__c,Name FROM Account]);
        for(CollegeApplication__c collegeApplication :  [SELECT Id,Name,College__c,Status__c,Deadline__c,WindowOpen__c,LoginPage__c,Username__c,Password__c,HomePage__c,YocketLink__c,College__r.Rating,IsInactive__c FROM CollegeApplication__c WHERE IsInactive__c = false AND College__c IN :mapInterestedColleges.keySet()]){
            lstCollegeApplicationWrapper.add(new CollegeApplicationWrapper(mapInterestedColleges.get(collegeApplication.College__c),collegeApplication,false));
        }
    }
    
    
    public Class CollegeApplicationWrapper{
        public Account college{get;set;}
        public CollegeApplication__c collegeApplication{get;set;}
        public Boolean expanded{get;set;}
        
        public CollegeApplicationWrapper(Account college,CollegeApplication__c collegeApplication,Boolean expanded){
            this.college =college;
            this.collegeApplication = collegeApplication;
            this.expanded = expanded;
        }
        
    }
    
    public PageReference makeRowEditable(){
        for(CollegeApplicationWrapper collegeApplicationobj : lstCollegeApplicationWrapper){
            if(rowCollegeAppId.equals(collegeApplicationobj.collegeApplication.Id)){
                collegeApplicationobj.expanded= true;
            }
        }
        return null;
    }
    
    public PageReference saveRow(){
        rowCollegeAppId = '';
        for(CollegeApplicationWrapper collegeApplicationobj : lstCollegeApplicationWrapper){
            if(rowCollegeAppSaveId.equals(collegeApplicationobj.collegeApplication.Id)){
                collegeApplicationobj.expanded= false;
            }
        }
        return null;
        
    }
    
    public PageReference cancel(){
        rowCollegeAppId = '';
        for(CollegeApplicationWrapper collegeApplicationobj : lstCollegeApplicationWrapper){
            if(rowCollegeAppCancelId.equals(collegeApplicationobj.collegeApplication.Id)){
                collegeApplicationobj.expanded= false;
            }
        }
        return null;
        
    }
}