src/objects/Company__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Designation__c</fullName>
        <label>Designation</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateEmployeeController.cls
public class CreateEmployeeController{
    public Employee__c employeeRecord{get;set;}
    public Company__c companyRecord{get;set;}
    public CreateEmployeeController(){
        employeeRecord = new Employee__c();
        Id companyId = System.currentPagereference().getParameters().get('cid');
        companyRecord = new Company__c();
        companyRecord = [SELECT Id,Name FROM Company__c WHERE Id = :companyId];
    }
    
    public PageReference save(){
        employeeRecord.Company__c = companyRecord.Id;
        if(employeeRecord.Name==null||employeeRecord.Designation__c==null||employeeRecord.Company__c==null||employeeRecord.Phone_Number__C==null||employeeRecord.Email__c==null){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please Enter all values before saving'));
            return null;
        }
        else{
            try{
                insert employeeRecord;
            }
            catch(Exception e){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please Enter all values before saving'+e.getMessage()));
                return null;
            }
            return new PageReference('/'+employeeRecord.Company__c);
        }    
    }    
    public PageReference cancel(){
        employeeRecord = null;
        return null;
    }
        
}