src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Company_Owner_Name__c</fullName>
        <label>Company Owner Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateCompanyController.cls
public class CreateCompanyController{
    public Company__c companyRecord {get;set;}
    
    public CreateCompanyController(){
        companyRecord = new Company__c();
    }
    public PageReference save(){
        if(companyRecord.Name==null||companyRecord.Address__c==null||companyRecord.Zip_Code__c==null||companyRecord.State__c == null||companyRecord.Country__c == null||companyRecord.Company_Owner_Name__c==null){
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please Enter all values before saving'));
             return null;
        }
        else{
            try{
                insert companyRecord;
            }
            catch(Exception e){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please Enter all values before saving'+e.getMessage()));
                return null;
            }    
            return new PageReference('/'+companyRecord.Id);
        }    
    }
    public PageReference saveAndEmployee(){
        if(companyRecord.Name==null||companyRecord.Address__c==null||companyRecord.Zip_Code__c==null||companyRecord.State__c == null||companyRecord.Country__c == null||companyRecord.Company_Owner_Name__c==null){
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please Enter all values before saving'));
             return null;
        }
        else{
            try{
                insert companyRecord;
            }
            catch(Exception e){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please Enter all values before saving'+e.getMessage()));
                return null;
            }    
            return new PageReference('/apex/CreateEmployee?cid='+companyRecord.Id);
        } 
    }
    public PageReference cancel(){
        companyRecord = null;
        return null;
    }
}