src/objects/Skill__c.object
<CustomObject>
    <fields>
        <fullName>Completion__c</fullName>
        <label>Completion</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>IsInactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsInactive</label>
        <type>Checkbox</type>
    </fields>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SkillsHighlightController.cls
public class SkillsHighlightController{
    public List<SkillWrapper> SkillWrapperList{get;set;}
    public skillsHighlightController(){
        SkillWrapperList = new List<SkillWrapper>();
        
        for(Skill__c skillRec : [SELECT Id,Name, IsInactive__c, Completion__c FROM Skill__c WHERE IsInactive__c = false]){
            SkillWrapperList.add(new SkillWrapper(skillRec));
        }
    }
    
    public class SkillWrapper{
        public Skill__c skill{get;set;}
        public Decimal completedPer{get;set;}
        public Decimal uncompletedPer{get;set;}
        
        public SkillWrapper(Skill__c skill){
            this.skill = skill;
            completedPer = skill.Completion__c;
            uncompletedPer = 100-completedPer;
        
        }
        
    
    }
    
}