src/objects/WebsiteUser__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Website User</label>
    <nameField>
        <displayFormat>User-{000000}</displayFormat>
        <label>Website User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Website Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UserRegistrationPageController.cls
public class UserRegistrationPageController {
    public WebsiteUser__c newUser{get;set;}
    public UserRegistrationPageController(){
        newUser = new WebsiteUser__c();
        
    }
    public PageReference createUser(){
        
        try{
            newUser.Active__c = true;
            insert newUser;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Login Successful. An email has been sent to your email Id. Kindly login'));
            return new PageReference('/apex/loginpage?newUser=1');
        }
        catch(Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,ex.getMessage()));
            return null;
        }
    }
}