src/objects/WebsiteUser__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>25</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <externalId>true</externalId>
        <label>UserName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Website User</label>
    <nameField>
        <displayFormat>User-{000000}</displayFormat>
        <label>Website User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Website Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LoginPageController.cls
public class LoginPageController{
    public String userName{get;set;}
    public String password{get;set;}
    public LoginPageController(){
        userName = '';
        password = '';
        if(ApexPages.currentPage().getParameters().get('newUser') == '1'){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'User Successfully created. Kindly login'));
        }
    }
    
    
    public void login(){
        List<WebsiteUser__c> lstWebsiteUsers = new List<WebsiteUser__c>([SELECT Id,Password__c FROM WebsiteUser__c Where (Username__c = :userName OR Email__c =:userName) AND Active__c = true]);
        if(lstWebsiteUsers.size() >0){
            if(lstWebsiteUsers[0].Password__c.equals(password)){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Login Successful.'));
            }
            else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Incorrect password'));
            }
        }
        else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,'No User with the user name - \'' + username + '\' found.'));
        }
    }
    
    public PageReference newUserRedirect(){
        PageReference pageRef = new PageReference('/apex/UserRegistrationPage');
        return pageRef;
    }
}